// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea1.Server.DAL;

#nullable disable

namespace Tarea1.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231030013029_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Tarea1.Shared.Prioridades", b =>
                {
                    b.Property<int>("PrioridadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DíasCompromiso")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrioridadID");

                    b.ToTable("Prioridades");
                });
#pragma warning restore 612, 618
        }
    }
}
